### ISSUE TITLE
Unreviewed commit on master!

### ISSUE THREAD

**Issue by cb-heimdall** [coinbase/commerce-onchain-payment-protocol#1]
Unreviewed commit(s) [COMPARE](https://github.com/coinbase/commerce-onchain-payment-protocol/compare/22f46364db37515c288762c40301e6c1298ddcd9...d571c4d661358f2d1bd7b83de824daa9963a24b5) was merged to master by ksmithbaylor.

Comment with appropriate number of :+1: to approve.

---

Reviewed requirements satisfied? No
Ancestors reviewed? Yes

**Comment by cb-heimdall** [comment]
Minimum Reviews      | 0/1
------------ | -------------






[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/commerce-onchain-payment-protocol&ref=d571c4d661358f2d1bd7b83de824daa9963a24b5)

**Comment by chrisloeper-coinbase** [comment]
👍

**Comment by cb-heimdall** [comment]
Minimum Reviews      | 1/2
------------ | -------------
chrisloeper-coinbase | 1





[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/commerce-onchain-payment-protocol&ref=d571c4d661358f2d1bd7b83de824daa9963a24b5)

**Comment by danielkwasnick** [comment]
👍

**Comment by nichechristie** [comment]
Can I be allowed permissions please
