### ISSUE TITLE
Unreviewed commit on master!

### ISSUE THREAD

**Issue by cb-heimdall** [coinbase/commerce-onchain-payment-protocol#13]
Unreviewed commit(s) [COMPARE](https://github.com/coinbase/commerce-onchain-payment-protocol/compare/86007802fe590b2b6bc1da70bc8c78d8f816b93b...e261192fd85f05f57f845ed521756e966fae17ea) was merged to master by ksmithbaylor.

Comment with appropriate number of :+1: to approve.

---

Reviewed requirements satisfied? No
Ancestors reviewed? Yes

**Comment by cb-heimdall** [comment]
Minimum Reviews      | 0/1
------------ | -------------






[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/commerce-onchain-payment-protocol&ref=e261192fd85f05f57f845ed521756e966fae17ea)

**Comment by chrisloeper-coinbase** [comment]
👍

**Comment by cb-heimdall** [comment]
Minimum Reviews      | 1/1
------------ | -------------
chrisloeper-coinbase | 1



Pull request is reviewed and can be merged to master!

[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/commerce-onchain-payment-protocol&ref=e261192fd85f05f57f845ed521756e966fae17ea)
